name=EspNowNetworkHostDriver
version=0.7.6
author=Johan Böhlin <github@johboh.dev>
maintainer=Johan Böhlin <github@johboh.dev>
sentence=Host driver code for the EspNowNetwork
paragraph=See https://github.com/Johboh/EspNowNetwork for more details.
category=Communication
url=https://github.com/Johboh/EspNowNetworkHostDriver
architectures=esp32
repository=https://github.com/Johboh/EspNowNetworkHostDriver.git
license=GPL-3.0-or-later
dependends=EspNowNetworkHost (>=0.8.2 && <1.0.0)
